In [1]:
import torch

In [4]:
position_ids = torch.arange(5)


In [5]:
position_ids

tensor([0, 1, 2, 3, 4])

# Mask test

In [35]:
att_mask = torch.tensor([[1, 1, 1, 1, 0, 0, 0, 0],[1, 1, 1, 1, 1, 1, 1, 1]])
att_mask = att_mask.unsqueeze(1).unsqueeze(1)
weights = torch.randn((2, 12, 8, 8))


In [ ]:
additive_mask = torch.where(att_mask == 0, torch.tensor(-float('inf')), 0)
masked_weights = weights + additive_mask
masked_weights = masked_weights * att_mask.transpose(-2, -1)

tensor([[[[-0.7061,  0.5732, -1.0800,  ...,  0.0782,  0.1263, -1.0744],
          [-1.0625,  1.0822,  0.6484,  ...,  0.8981, -2.0683,  0.6786],
          [-0.2612,  0.3801, -0.4651,  ...,  1.1320, -0.5527,  0.9533],
          ...,
          [ 0.2035,  1.4884,  1.2737,  ..., -3.0958, -0.3054,  1.5340],
          [ 1.3399, -0.8621,  0.4321,  ...,  1.0230,  1.3014,  0.9812],
          [ 1.9752, -1.0891,  0.0690,  ...,  0.9891, -0.3789, -1.1874]],

         [[ 0.8451, -1.0214, -0.9644,  ..., -0.3847, -0.3511,  1.6449],
          [ 0.8504,  0.5936, -0.4431,  ...,  0.5255, -1.2300, -1.5925],
          [ 0.4621,  1.5571, -0.1834,  ...,  0.3426,  1.1564, -0.8045],
          ...,
          [-0.3544, -0.9883,  0.6968,  ..., -0.6774, -0.1888,  1.6992],
          [ 0.3452, -0.4538,  1.2829,  ..., -1.7412,  0.3208, -0.9231],
          [ 0.2039, -0.7232, -2.2454,  ...,  1.5857,  0.8136,  0.1007]],

         [[-0.0154,  1.1498, -0.2074,  ...,  0.3930,  2.2204, -0.8781],
          [-1.6000,  1.6949, -

In [ ]:
import math
negative_mask = (att_mask == 0)
final_mask = 

In [58]:
negative_mask.bool()

tensor([[[[False, False, False, False,  True,  True,  True,  True]]],


        [[[False, False, False, False, False, False, False, False]]]])

In [62]:
additive_mask.transpose(-1, -2)

tensor([[[[0.],
          [0.],
          [0.],
          [0.],
          [-inf],
          [-inf],
          [-inf],
          [-inf]]],


        [[[0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.],
          [0.]]]])